/*

    _______   _    __ __
   /\  ___ \/\ \  /| |\_\
   \ \ \_/\_\ \ \ || |/_/
    \ \ \\/_/\ \ \|| |  __     __  __        __
     \ \ \   _\ \ \| | /\ \  /'__'\\ \  /\  / /
      \ \ \__\ \ \   | \ \ \/\  __/ \ \/  \/ /
       \ \______\ \__|  \ \_\ \____\ \__/\__/
        \/______/\/__/   \/_/\/____/\/__\/_/

           A window library for Allegro

 (c) By Stefan Schimanski & Janko Heilgeist '1997/1998


                  1Stein@gmx.de
              Janko.Heilgeist@gmx.de

            http://1Stein.home.pages.de

 -----------------------------------------------------

 view.h - Main header file

*/


#ifndef VIEW_H_INCLUDED
#define VIEW_H_INCLUDED

/* standard include files -------------------------------------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* allegro include files --------------------------------------------------*/
//#include <allegro.h>

/* library include files --------------------------------------------------*/
#include "v_const.h"
#include "v_string.h"
#include "v_gfx.h"
#include "v_common.h"
#include "v_mouse.h"
#include "v_base.h"
#include "v_utils.h"
#include "v_input.h"
#include "v_button.h"
#include "v_scroll.h"
#include "v_dialog.h"
#include "v_list.h"
#include "v_combo.h"
#include "v_prog.h"
#include "v_menu.h"
#include "v_msg.h"
#include "v_file.h"
#include "v_radio.h"
#include "v_text.h"
#include "v_check.h"
#include "v_proces.h"
#include "v_pictur.h"
#include "v_color.h"
#include "v_macro.h"
#include "v_border.h"
#include "v_system.h"
#include "v_sysbit.h"
#include "v_string.h"
#include "v_vidmode.h"
#include "v_infdlg.h"
#include "v_picdlg.h"
#include "v_save.h"
#include "v_load.h"
#include "v_comman.h"

#endif
